### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by alterechtschreibung** [zagayevskiy/Pacman#2]
Doesn’t build the native libraries; I’ve tried at several commits with different toolchains. The error at v1.1 is:
Compile++ thumb  : pacman <= pacmanlib.cpp
jni/pacmanlib.cpp:17:35: fatal error: android/asset_manager.h: No such file or directory
compilation terminated.
make: **\* [obj/local/armeabi/objs/pacman/pacmanlib.o] Error 1

**Comment by zagayevskiy** [comment]
Add "%NDK_ROOT%/platforms/android-9/arch-arm/usr/lib" and "%NDK_ROOT%/platforms/android-9/arch-arm/usr/include" to your compiler includes path. For example, Eclipse solution: Project Properties->C/C++ General/Includes->Add...

**Comment by alterechtschreibung** [comment]
Fixed but get errors that occur with most previous commits:
- /home/gerry/android-ndk-r9/ndk-build -I /home/gerry/android-ndk-r9/platforms/android-9/arch-arm/usr/lib -I /home/gerry/android-ndk-r9/platforms/android-9/arch-arm/usr/include
  jni/managers/Art.cpp: In static member function 'static void Art::loadTextures()':
  jni/managers/Art.cpp:490:2: error: format not a string literal and no format arguments [-Werror=format-security]
  cc1plus: all warnings being treated as errors

**Comment by zagayevskiy** [comment]
[Art.cpp: 490]  LOGI(buffer);
LOGI just a simple log macro, defined in jni/log.h
Solutions:
1)Remove Art.cpp: 490 line
2)Or change jni/log.h like this: #define LOGI(...) //No log output!
3)Or remove -Werror arg from your compilers's command.

**Comment by alterechtschreibung** [comment]
Thank you.
